name: Complex

on: push

jobs:
  job-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
    
  job-windows:
    runs-on: windows-latest
    steps:
    - run: date
    
  job-macos:
    runs-on: macos-latest
    steps:
    - run: date
    
  job-dependant:
    runs-on: ubuntu-latest
    steps:
    - run: date
    needs: [job-ubuntu, job-windows, job-macos]
